spring.application.name=IOT-Backend
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/monitor?useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Home Assistant API Configuration
ha.api.url=http://74.48.62.239:443
ha.api.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwOWU2YmNjMWRmMTI0ZTUyODA2YTJhYTdiNjYzNDkzNyIsImlhdCI6MTc2NDkyMTkwMiwiZXhwIjoyMDgwMjgxOTAyfQ.DOoCIV6TWKNBgSHWNBOHREMLfcnFBQYhS2r0ud1qhT4
